name: Deploy Ke VM Linux

# Pipeline ini akan jalan setiap kali ada push ke branch 'main'
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Langkah 1: Ambil code terbaru dari GitHub repository
    - name: Checkout Code
      uses: actions/checkout@v4

    # Langkah 2: Kirim file ke VM Linux menggunakan SSH & rsync
    - name: Deploy to VM via SSH
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.VM_HOST }}
        username: ${{ secrets.VM_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: "index.html" # File yang mau dikirim
        target: "/var/www/html" # Folder tujuan di VM Linux
