name: Deploy Ke VM Linux Lokal

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Copy Files to Web Directory
      run: |
        cp index.html /var/www/html/