name: Deploy Ke VM Linux Lokal

# Pipeline ini akan jalan setiap kali ada push ke branch 'main'
on:
  push:
    branches:
      - main

jobs:
  deploy:
    # 1. WAJIB GANTI INI: Menyuruh GitHub menjalankan pipeline di VM lokal kamu
    runs-on: self-hosted

    steps:
    # 2. Langkah 1: Runner di VM kamu akan mendownload kode terbaru dari GitHub
    - name: Checkout Code
      uses: actions/checkout@v4

    # 3. Langkah 2: Menyalin file langsung ke folder Nginx karena runner sudah ada di dalam VM
    - name: Copy Files to Web Directory
      run: |
        cp index.html /var/www/html/